### ISSUE TITLE
How to get gaze direction from heatmap, especially for out of image traget?

### ISSUE THREAD

**Issue by XiaoLuoLYG** [fkryan/gazelle#2]
the model only output heatmap and in/out confidence, is there a way to convert this to the gaze direction, for example a vector or yaw,pitch angle (especially if the gaze target not in the image/looking out).

 Also any plan to release training code?

**Comment by fkryan** [comment]
Our model is not designed for the task of 3D gaze direction prediction (pitch & yaw), which is a separate task. There are several existing training datasets / benchmarks for this task such as Gaze360, ETH-XGaze, Eyediap, MPII-Gaze, etc. so for your use case, I would recommend looking into models trained on those datasets. Here is one such codebase: https://github.com/zgchen33/MCGaze

We will consider releasing training code.
